### ISSUE TITLE
Issue when getting the first in the list

### ISSUE THREAD

**Issue by tperale** [thomacer/zflix#13]
Traceback (most recent call last):
  File "zflix.py", line 238, in <module>
    main(option)
  File "zflix.py", line 142, in main
    torrentToStream = pageLink['ref'].get_magnet(pageLink['link'])
  File "/home/thomas/Documents/zflix/src/trackers/torrentz.py", line 217, in get_magnet
    magnet = self.get_magnet_from_tracker(trackerPage)
  File "/home/thomas/Documents/zflix/src/trackers/torrentz.py", line 150, in get_magnet_from_tracker
    if 'magnet:' in urls[i].get('href'):
IndexError: list index out of range

**Comment by tperale** [comment]
https://github.com/thomacer/zflix/commit/43ff5a31776be43e671784dbef2ce9de3a80a963
